config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about" => "homes#about", as: 'about'
  resources :books
  resources :users, only: [:index,:show,:edit,:update]

end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_current_user, only:[:edit,:update,:destroy]

  def new
    @book = Book.new
    @user = @book.user
  end

  def create
    @book = Book.new(book_params)
    @user = current_user
    @book.user_id = current_user.id
    @books = Book.all
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user

  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

  def is_current_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
    <%= @book.errors.count %> errors prohibited this obj from being saved:
    <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

<div class = "container">
    <div class = "row">
        <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

        <h1>Editing Book</h1>

        <%= form_with model: @book do |f| %>
        <div class = "form-group">
            <label for ="book_title">Title</label><br />
            <%= f.text_field :title %>
        </div>
        <div class = "form-group">
            <label for = "book_opinion">Opinion</label><br />
            <%= f.text_area :body %>
        </div>
        <div class = "form-group">
            <%= f.submit 'Update Book',class:"btn btn-success" %>
        </div>
        <% end %>
        <%= link_to "Show", book_path(@book.id) %> |
        <%= link_to "Back", books_path %>
    </div>
</div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
    <%= @book.errors.count %> errors prohibited this obj from being saved:
    <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

<div class = "container px-5 px-sm-0">
  <div class = "row">
    <div class = "col-md-3">

<h2>User Info</h2>
  <%= image_tag @user.get_profile_image(100,100) %>
  <table class = "table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>Introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class = "row">
    <div class = "btn btn-outline-secondary btn-block">
      <%= link_to edit_user_path(@user) do %>
    <i class="fas fa-user-cog" style="color: #b0b0b0;"></i>
    <% end %>
    </div>
  </div>

<h2 class = "mt-3">New book</h2>

<%= form_with model: @book do |f| %>

<div class = "form-group">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>

<div class = "form-group">
  <%= f.label 'Opinion' %><br />
  <%= f.text_area :body %>
</div>

<div class = "form-group">
  <%= f.submit 'Create Book',class:"btn btn-success" %>
</div>

<% end %>
</div>

<div class = "col-md-8 offset-md-1">
  <h2>books</h2>
  <table class = "table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan = "3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image(100,100) %>
          <% end %>
        </td>
        <td>
          <%= link_to book.title, book_path(book.id) %>
        </td>
        <td>
          <%= book.body %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  </div>
  </div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= form_with model: @book do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_area :body %>
<%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div class = "container px-5 px-sm-0">
  <div class = "row">
    <div class = "col-md-3">

<h2>User Info</h2>
  <%= image_tag @book.user.get_profile_image(100,100) %>
  <table class = "table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= @book.user.name %></th>
      </tr>
      <tr>
        <th>Introduction</th>
        <th><%= @book.user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class = "row">
    <div class = "btn btn-outline-secondary btn-block">
      <%= link_to edit_user_path(@user) do %>
    <i class="fas fa-user-cog" style="color: #b0b0b0;"></i>
    <% end %>
    </div>
  </div>

<h2 class = "mt-3">New book</h2>

<%= form_with model: @book_new do |f| %>

<div class = "form-group">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>

<div class = "form-group">
  <%= f.label 'Opinion' %><br />
  <%= f.text_area :body %>
</div>

<div class = "form-group">
  <%= f.submit 'Create Book',class:"btn btn-success" %>
</div>

<% end %>
</div>

<div class = "col-md-8 offset-md-1">
<h2>Book detail</h2>
<table class = "table">
  <tbody>
    <tr>
      <td>
      <%= link_to user_path(@book.user.id) do %>
      <%= image_tag @book.user.get_profile_image(100,100) %><br />
      <%= @book.user.name %>
      <% end %>
      </td>

      <td>
        <%= link_to @book.title,book_path(@book.id) %>
      </td>
      <td>
        <%= @book.body %>
      </td>
      <% if @book.user == current_user %>
      <td>
        <button type="button" class="btn btn-success">
          <%= link_to "Edit", edit_book_path(@book.id),class:"text-light" %>
      </button>
    </td>
    <td>
      <button type="button" class="btn btn-danger">
        <%= link_to "Destroy", book_path(@book.id), method: :delete, "date-confirm" => "本当に削除しますか？",class:"text-light" %>
      </button>
    </td>
  <% end %>
  </tr>
  </tbody>
  </table>
  </div>
</div>
</div>