config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about" => "homes#about", as: 'about'
  resources :books
  resources :users, only: [:index,:show,:edit,:update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-expand-md bg-dark navbar-dark bg-dark">
        <div class = "container">
          <a class = "navbar-brand" href = "/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class = "nav-link text-light">
              <%= link_to user_path(current_user.id), class:"text-light" do %>
                <i class="fas fa-home" style="color: #ffffff;"></i>Home
              <% end %>
            </li>
            <li class = "nav-link text-light">
              <%= link_to users_path, class:"text-light" do %>
                <i class="fas fa-users" style="color: #ffffff;"></i>Users
              <% end %>
            </li>
            <li class = "nav-link text-light">
              <%= link_to books_path, class:"text-light" do %>
                <i class="fas fa-book-open" style="color: #ffffff;"></i>Books
              <% end %>
            </li>
            <li class = "nav-link text-light">
              <%= link_to destroy_user_session_path,method: :delete, class:"text-light" do %>
                <i class="fas fa-sign-out-alt" style="color: #ffffff;"></i>Log out
              <% end %>
            </li>
           <% else %>
            <li class = "nav-link text-light">
              <%= link_to '/', class:"text-light" do %>
                <i class="fas fa-home" style="color: #ffffff;"></i>Home
              <% end %>
            </li>
            <li class = "nav-link text-light">
              <%= link_to about_path, class:"text-light" do %>
                <i class="fas fa-link" style="color: #ffffff;"></i>About
              <% end %>
            </li>
            <li class = "nav-link text-light">
              <%= link_to new_user_registration_path, class:"text-light" do %>
                <i class="fas fa-user-plus" style="color: #ffffff;"></i>Sign up
               <% end %>
            </li>
            <li class = "nav-link text-light">
              <%= link_to new_user_session_path, class:"text-light" do %>
                <i class="fas fa-sign-in-alt" style="color: #ffffff;"></i>Log in
              <% end %>
            </li>
           <% end %>
          </ul>
         </div>
        </div>
      </div>
    </header>

    <p class = "notice"><%= notice %></p>
    <p class = "alert"><%= alert %></p>
    <%= yield %>

    <footer>
      <div class = "container mt-5">
        <div class = "row">
          <div class = "mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>